sahibinden/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('auth/', include('allauth.urls')),
                  path('user/', include('advertise.urls.user'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advertise/models/user.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from advertise.choices import GenderChoices, MartialStatusChoices, EducationalStatusChoices, ProfessionChoices
from advertise.helpers import upload_to_user


class Interest(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class User(AbstractUser):
    birthday = models.DateField(null=True)
    phone_number = models.CharField(max_length=15, null=True)
    gender = models.PositiveIntegerField(null=True, choices=GenderChoices.CHOICES)
    marital_status = models.PositiveIntegerField(null=True, choices=MartialStatusChoices.CHOICES)
    educational_status = models.PositiveIntegerField(null=True, choices=EducationalStatusChoices.CHOICES)
    profession = models.PositiveIntegerField(null=True, choices=ProfessionChoices.CHOICES)
    interests = models.ManyToManyField(to=Interest)
    image = models.ImageField(null=True, blank=True, upload_to=upload_to_user)

    class Meta:
        verbose_name = "User"

    @property
    def profile_image(self):
        return "/static/img/profile-placeholder.jpg"

    @property
    def info(self):
        full_name = self.get_full_name() or "-"
        birthday = self.birthday or "-"
        gender = self.get_gender_display() or "-"
        marital_status = self.get_marital_status_display() or "-"
        educational_status = self.get_educational_status_display() or "-"
        profession = self.get_profession_display() or "-"
        interests = ", ".join([interest.name for interest in self.interests.all()]) or "-"
        phone_number = self.phone_number or "-"

        context = {
            'username': self.username,
            'full_name': full_name,
            'birthday': birthday,
            'gender': gender,
            'marital_status': marital_status,
            'educational_status': educational_status,
            'profession': profession,
            'interests': interests,
            'phone_number': phone_number
        }

        return context

advertise/forms/user.py
import re
from datetime import datetime

from django import forms

from advertise.choices import GenderChoices
from advertise.models import User


class UpdateUserForm(forms.ModelForm):
    birthday = forms.DateTimeField(
        label="Doğum Tarihi",
        input_formats=['%d/%m/%Y'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control',
            'data-target': '#id_birthday',
            'data-toggle': "datetimepicker",
        })
    )

    gender = forms.ChoiceField(label="Cinsiyet", choices=GenderChoices.CHOICES, widget=forms.RadioSelect, required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'birthday', 'gender',
                  'marital_status', 'educational_status', 'profession',
                  'interests', 'phone_number']

        widgets = {
            'interests': forms.CheckboxSelectMultiple,
        }

        labels = {
            'marital_status': "Medeni Hali",
            'educational_status': "Eğitim Durumu",
            'profession': "Meslek",
            'interests': "İlgi Alanları",
            'phone_number': "Telefon Numarası",
        }

    def clean_birthday(self):
        cleaned_data = self.cleaned_data.get('birthday')

        if datetime.now().year - cleaned_data.year < 15:
            raise forms.ValidationError("15 yaşından küçük kullanıcıların kullanması uygun değildir.")
        return cleaned_data

    def clean_phone_number(self):
        cleaned_data = self.cleaned_data.get('phone_number')
        regex = re.compile(r'\d+')

        phone_number_list = regex.findall(cleaned_data)
        phone_number = "".join(phone_number_list)

        if len(phone_number) != 10:
            raise forms.ValidationError("Lütfen Telefon Numarası Giriniz.")

        return cleaned_data

advertise/views/user.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.decorators.http import require_http_methods

from advertise.forms import UpdateUserForm
from advertise.models import User


@require_http_methods(["GET", "POST"])
def edit_user(request, username):
    user = get_object_or_404(User, username=username)

    if request.method == "POST":
        form = UpdateUserForm(instance=user, data=request.POST or None)
        if form.is_valid():
            user = form.save(commit=True)
            user_retrieve = render_to_string('user/includes/retrieve.html', context=user.info, request=request)
            return JsonResponse(data={'status': 'success', 'user_retrieve': user_retrieve})
        else:
            string_form = render_to_string('user/includes/edit-form.html', context={'form': form}, request=request)
            return JsonResponse(data={'status': 'fail', 'string_form': string_form})

    form = UpdateUserForm(instance=user)
    string_form = render_to_string('user/includes/edit-form.html', context={'form': form}, request=request)
    return JsonResponse(data={'string_form': string_form})


@require_http_methods(["GET"])
def retrieve(request, username):
    users = User.objects.prefetch_related('interests')
    user = get_object_or_404(users, username=username)

    if request.is_ajax():
        user_retrieve = render_to_string('user/includes/retrieve.html', context=user.info, request=request)
        return JsonResponse(data={'user_retrieve': user_retrieve})

    return render(request, 'user/retrieve.html', context=user.info)

templates/user/base.html
{% extends 'base.html' %}
{% block content %}
    <div class="clearfix"></div>
    <div id="content">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col col-lg-12 col-xl-10">
                    <div class="row has-sidebar">
                        <div class="col-md-5 col-lg-4 col-xl-4 col-sidebar">
                            <div id="sidebar" class="sidebar-left">
                                <div class="sidebar_inner">
                                    <div class="list-group no-border list-unstyled">
                                        <span class="list-group-item heading">Hesabı Yönet</span>
                                        <a href="{% url 'retrieve' request.user.username %}" class="list-group-item {% if request.resolver_match.url_name == "retrieve" %} active {% endif %}  "><i class="fa fa-fw fa-pencil"></i>Kişisel Bilgiler</a>
                                        <a href="{% url 'account_change_password' %}" class="list-group-item {% if request.resolver_match.url_name == "account_change_password" %} active {% endif %} "><i class="fa fa-fw fa-lock"></i>Şifre Değiştir</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7 col-lg-8 col-xl-8">

                            <div class="theiaStickySidebar" style="padding-top: 1px; padding-bottom: 1px; position: static; transform: none;">
                                <div class="page-header bordered">
                                    <h1>{% block sub_title %} {% endblock %}</h1>
                                </div>
                            </div>
                            {% block sub_content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/retrieve.html
{% extends 'user/base.html' %}

{% block static_contanier %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css"/>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>

    <style type="text/css">
        ul.interests li {
            display: inline-block;
            width: 24.5%;
        }

        ul.gender li {
            display: inline-block;
            width: 24.5%;
        }
    </style>


    <script>
        $(document).ready(function () {

            $(this).on('click', "#retrieve-edit-form", function (e) {
                e.preventDefault();
                var $this = $(this);
                var $url = $this.attr('edit-url');
                $.getJSON($url, null, function (data, status, jqXGR) {
                    $this.closest('#user_container').html(data.string_form);
                    $("#id_birthday").datetimepicker({
                        format: 'DD/MM/YYYY',
                        locale: "tr"
                    });

                    $('#id_phone_number').usPhoneFormat({
                        format: '(xxx) xxx-xxxx',
                    });
                })
            });


            $(this).on('click', "#user_update_cancel_button", function (e) {
                e.preventDefault();
                var $this = $(this);
                var $url = $this.attr('href');
                $.getJSON($url, null, function (data, status, jqXGR) {
                    $this.closest('#user_container').html(data.user_retrieve);
                })
            });


            $(this).on('submit', "#user-edit-form", function (e) {
                e.preventDefault();
                var $this = $(this);
                var $data = $this.serialize();
                var $url = $this.attr('action');

                $.post($url, $data, function (data, status, jqXHR) {

                    if (data.status === "success") {
                        $this.closest('#user_container').html(data.user_retrieve);
                        alertify.set('notifier', 'position', 'bottom-left');
                        alertify.notify('Profil bilgileri güncellendi', 'success', 5);

                        return 1;
                    }

                    $this.closest('#user_container').html(data.string_form);

                    $("#id_birthday").datetimepicker({
                        format: 'DD/MM/YYYY',
                        locale: "tr"
                    });

                    $('#id_phone_number').usPhoneFormat({
                        format: '(xxx) xxx-xxxx',
                    });

                });

            })


        })
    </script>
{% endblock %}


{% block sub_title %} Kişisel Bilgileri {% endblock %}


{% block sub_content %}
    <div id="user_container" class="font-weight-bold">
        {% include 'user/includes/retrieve.html' %}
    </div>
{% endblock %}